<?php
return array (
  1 => 
  array (
    'id' => '1',
    'catid' => '302',
    'typeid' => '0',
    'title' => '测试',
    'style' => '',
    'thumb' => '',
    'keywords' => '测试',
    'description' => '测试',
    'posids' => '0',
    'url' => 'http://zx.ikongjian.com/index.php?m=content&c=index&a=show&catid=302&id=1',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1480406102',
    'updatetime' => '1480407208',
    'hitsid' => 'c-1-1',
    'views' => '11',
    'yesterdayviews' => '0',
    'dayviews' => '11',
    'weekviews' => '11',
    'monthviews' => '11',
  ),
  2 => 
  array (
    'id' => '2',
    'catid' => '302',
    'typeid' => '0',
    'title' => '测试2',
    'style' => '',
    'thumb' => 'http://zx.ikongjian.com/uploadfile/2016/1129/20161129042411352.jpg',
    'keywords' => '测试2',
    'description' => '测试2',
    'posids' => '0',
    'url' => 'http://zx.ikongjian.com/index.php?m=content&c=index&a=show&catid=302&id=2',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1480407148',
    'updatetime' => '1480407162',
    'hitsid' => 'c-1-2',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  3 => 
  array (
    'id' => '3',
    'catid' => '302',
    'typeid' => '0',
    'title' => '家装地砖瓷砖挑选应注意事项',
    'style' => '',
    'thumb' => 'http://zx.ikongjian.com/uploadfile/2016/1129/20161129042327426.jpg',
    'keywords' => '测试3',
    'description' => '家装地砖瓷砖挑选有学问，由于地砖要用很多年，一时节省，买了小厂家不耐磨的瓷砖，一年后砖表面斑斑驳驳、裂纹横生、不堪入目，即不耐用，又不环保，在这里，专家建议您选择正规厂家',
    'posids' => '0',
    'url' => 'http://zx.ikongjian.com/index.php?m=content&c=index&a=show&catid=302&id=3',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1480407174',
    'updatetime' => '1480407183',
    'hitsid' => 'c-1-3',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>